#!/usr/bin/env python3
"""
Security Setup Script for Credit Risk Management API

This script helps generate secure configuration values and validates
security settings before deployment.

Usage:
    python scripts/security_setup.py
"""

import secrets
import hashlib
import os
from pathlib import Path


def generate_api_key():
    """Generate a cryptographically secure API key."""
    api_key = secrets.token_urlsafe(32)
    print(f"\n🔑 Generated API Key:")
    print(f"   {api_key}")
    print(f"\n⚠️  IMPORTANT: Save this key securely! It won't be shown again.")
    return api_key


def generate_sha256(filepath):
    """Generate SHA256 hash for a file."""
    if not os.path.exists(filepath):
        print(f"❌ File not found: {filepath}")
        return None
    
    sha256_hash = hashlib.sha256()
    with open(filepath, "rb") as f:
        for chunk in iter(lambda: f.read(4096), b""):
            sha256_hash.update(chunk)
    
    return sha256_hash.hexdigest()


def generate_model_hashes():
    """Generate SHA256 hashes for all model files."""
    models_dir = Path(__file__).parent.parent / "src" / "models" / "outputs"
    
    print("\n📦 Generating Model Hashes...")
    print("=" * 60)
    
    model_files = {
        "scaler.pkl": "SCALER_SHA256",
        "random_forest_model.pkl": "RANDOM_FOREST_SHA256",
        "gradient_boosting_model.pkl": "GRADIENT_BOOSTING_SHA256",
        "neural_network_model.h5": "NEURAL_NETWORK_SHA256"
    }
    
    hashes = {}
    for filename, env_var in model_files.items():
        filepath = models_dir / filename
        if filepath.exists():
            hash_value = generate_sha256(filepath)
            hashes[env_var] = hash_value
            print(f"✅ {filename}:")
            print(f"   {hash_value}")
        else:
            print(f"⚠️  {filename} not found (skipping)")
    
    return hashes


def create_env_file(api_key, model_hashes):
    """Create .env file with generated values."""
    env_template = """# Credit Risk Management API - Environment Variables
# Generated by security_setup.py
# ⚠️  NEVER commit this file to Git!

### Security Configuration
API_ENV=prod
API_KEY={api_key}

### Server Configuration
API_HOST=127.0.0.1
API_PORT=8001

### CORS Configuration (update with your actual domains)
API_ALLOWED_ORIGINS=https://your-frontend-domain.com,https://houssam-source-credit-risk-manager-app.streamlit.app

### Request Size Limit (bytes)
MAX_REQUEST_BYTES=262144

### Model Integrity Verification
SCALER_SHA256={scaler_hash}
RANDOM_FOREST_SHA256={rf_hash}
GRADIENT_BOOSTING_SHA256={gb_hash}
NEURAL_NETWORK_SHA256={nn_hash}

### Inference Logging
INFERENCE_LOG_PATH=data/monitoring/inference_window.csv
INFERENCE_LOG_MAX_ROWS=10000
INFERENCE_LOG_PRUNE_EVERY=200
"""
    
    env_content = env_template.format(
        api_key=api_key,
        scaler_hash=model_hashes.get('SCALER_SHA256', ''),
        rf_hash=model_hashes.get('RANDOM_FOREST_SHA256', ''),
        gb_hash=model_hashes.get('GRADIENT_BOOSTING_SHA256', ''),
        nn_hash=model_hashes.get('NEURAL_NETWORK_SHA256', '')
    )
    
    env_path = Path(__file__).parent.parent / ".env"
    
    if env_path.exists():
        backup_path = Path(__file__).parent.parent / ".env.backup"
        import shutil
        shutil.copy2(env_path, backup_path)
        print(f"\n💾 Backed up existing .env to .env.backup")
    
    with open(env_path, "w") as f:
        f.write(env_content)
    
    print(f"\n✅ Created .env file at: {env_path}")
    print("⚠️  REMINDER: Update API_ALLOWED_ORIGINS with your actual domain!")


def create_streamlit_secrets(api_key):
    """Create Streamlit secrets.toml file."""
    secrets_template = """# Streamlit Secrets Configuration
# Generated by security_setup.py
# ⚠️  NEVER commit this file to Git!

# API Configuration
API_URL = "http://localhost:8001"
API_KEY = "{api_key}"

# Session Secret (for future use)
SESSION_SECRET = "{session_secret}"
""".format(
        api_key=api_key,
        session_secret=secrets.token_urlsafe(32)
    )
    
    secrets_dir = Path(__file__).parent.parent / ".streamlit"
    secrets_path = secrets_dir / "secrets.toml"
    
    with open(secrets_path, "w") as f:
        f.write(secrets_template)
    
    print(f"✅ Created Streamlit secrets at: {secrets_path}")


def validate_security_config():
    """Validate security configuration."""
    print("\n🔍 Validating Security Configuration...")
    print("=" * 60)
    
    env_path = Path(__file__).parent.parent / ".env"
    
    if not env_path.exists():
        print("❌ .env file not found!")
        print("   Run 'python scripts/security_setup.py' first")
        return False
    
    # Read and validate
    with open(env_path) as f:
        content = f.read()
    
    checks = {
        "API_ENV=prod": "Production mode enabled",
        "API_KEY=": "API key configured",
        "API_ALLOWED_ORIGINS=": "CORS origins configured",
        "SCALER_SHA256=": "Scaler hash configured",
        "RANDOM_FOREST_SHA256=": "Random Forest hash configured",
        "GRADIENT_BOOSTING_SHA256=": "Gradient Boosting hash configured",
    }
    
    all_good = True
    for check, message in checks.items():
        if check in content:
            print(f"✅ {message}")
        else:
            print(f"❌ {message} - MISSING")
            all_good = False
    
    # Check for default values
    if "change-me" in content.lower() or "your-" in content.lower():
        print("\n⚠️  WARNING: Default placeholder values detected!")
        print("   Replace all 'your-*' and 'change-me' values with real secrets")
        all_good = False
    
    return all_good


def main():
    """Main setup function."""
    print("🔒 Credit Risk Management - Security Setup")
    print("=" * 60)
    
    # Generate API key
    api_key = generate_api_key()
    
    # Generate model hashes
    model_hashes = generate_model_hashes()
    
    # Create configuration files
    create_env_file(api_key, model_hashes)
    create_streamlit_secrets(api_key)
    
    # Validate configuration
    is_valid = validate_security_config()
    
    print("\n" + "=" * 60)
    if is_valid:
        print("✅ Security setup complete!")
        print("\n📋 Next steps:")
        print("   1. Review .env file and update API_ALLOWED_ORIGINS")
        print("   2. Commit only .env.example (NOT .env)")
        print("   3. Deploy with confidence! 🚀")
    else:
        print("⚠️  Security setup has issues that need attention")
        print("   Review the errors above and fix them manually")
    
    print("\n📚 For more details, see SECURITY.md")
    print("=" * 60)


if __name__ == "__main__":
    main()
